version: "3.8"

networks:
  traefik_web:
    external: true
  internal:
    external: false

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    env_file:
      - mongo.env
    volumes:
      - ./database/db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - internal
    labels:
      - traefik.enable=false
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: unless-stopped
    labels:
      - traefik.http.routers.mongo-express.rule=Host(`mongo-express.scotex.tech`)
      - traefik.http.routers.mongo-express.tls=true
      - traefik.http.routers.mongo-express.tls.certresolver=lets-encrypt
      - traefik.port=8090
    expose:
      - '8090'
    links:
        - mongodb
    networks:
      - internal
      - traefik_web
    env_file:
      - mongo-express.env
    depends_on:
      - mongodb
  api:
    container_name: api
    restart: unless-stopped
    build:
      context: server
    networks:
      - internal
    env_file:
      - api.env
    labels:
      - traefik.enable=false
    depends_on:
      - mongodb
  web:
    container_name: web
    restart: unless-stopped
    build:
     context: GroceryList.Client
    env_file:
      - web.env
    labels:
      - traefik.http.routers.web.rule=Host(`grocery-list.scotex.tech`)
      - traefik.http.routers.web.tls=true
      - traefik.http.routers.web.tls.certresolver=lets-encrypt
    networks:
      - internal
      - traefik_web
    depends_on:
      - api